### ISSUE TITLE
Floating point decimal number

### ISSUE THREAD

**Issue by tridiserkan** [hschendel/stl#4]
Hi, I guess this is causing from me but I could not change vertex point decimal numbers to 2 from 7. Even when I take solid as a variable from pointer, after few lines which are pretty sure making changes on my slices not on "stl.Solid" datatype, both my slices and solid pointer change values back. 

If I could been able to change decimal coding to 2 from 7 it would be okay for me right now. Did you do this in writebinary.go?

**Comment by hschendel** [comment]
Hi @tridiserkan,

is this about the decimal precision of the STL ASCII output?
Can you maybe provide an example?

**Comment by tridiserkan** [comment]
It's probably because that I am a newbie in GO and couldn't be able to process data outside of pointer but I think it could be about STL ASCII output too. When I debug I saw that even I take data into a variable and leave pointer stl.Solid be, when I process quicksort function of mine, points change in solid variable too. Here is a snippet of my code I shortened it so functions now takes pointer as input.



package main

import (
"fmt"
"math"
"os"
"stl-master"
"time"
)

type coords struct{
	x_coord map[stl.Vec3]float64
	y_coord map[stl.Vec3]float64
	z_coord map[stl.Vec3]float64
}

type cordy struct {
	triangle []float32
	verty []float32
	value []float32
}

func main() {

	var filePath = "/home/serkan/Desktop/tridi_models/stl/"

	solid, errRead := stl.ReadFile(filePath + "moon_city_final.stl")
	if errRead != nil {
		fmt.Fprintln(os.Stderr, errRead)
		os.Exit(1)
	}

	solidy := round_points(solid)

	var x_coords [][3]float64
	var y_coords [][3]float64
	var z_coords [][3]float64

	x_coords, y_coords, z_coords = coord_slice(solidy)

	sorted_x := quicksort(x_coords)
	sorted_y := quicksort(y_coords)
	sorted_z := quicksort(z_coords)

	fmt.Println(len(sorted_x), len(sorted_y), len(sorted_z))

}

func round_points(arr *stl.Solid) *stl.Solid {
	var num_mesh = len(arr.Triangles)
	var tx float32
	var ty float32
	var tz float32
	solidy := arr

	for i := 0; i < num_mesh; i++ {
		for j := 0; j < 3; j++ {
			tx = float32(math.Floor(float64(solidy.Triangles[i].Vertices[j][0]*100)) / 100)
			solidy.Triangles[i].Vertices[j][0] = tx
			ty = float32(math.Floor(float64(solidy.Triangles[i].Vertices[j][1]*100)) / 100)
			solidy.Triangles[i].Vertices[j][1] = ty
			tz = float32(math.Floor(float64(solidy.Triangles[i].Vertices[j][2]*100)) / 100)
			solidy.Triangles[i].Vertices[j][2] = tz
			if i == 97 {
				fmt.Println("debug")
			}
		}
	}
}

func quicksort(arr [][3]float64) [][3]float64 {

	var low [][3]float64
	var high [][3]float64
	var equal [][3]float64
	var result [][3]float64

	if len(arr)>1 {
		pivot := arr[0][2]
		for i := 0; i < len(arr); i++ {
			if arr[i][2] < pivot {
				low = append(low, arr[i])
			}
			if arr[i][2] > pivot {
				high = append(high, arr[i])
			}
			if arr[i][2] == pivot {
				equal = append(equal, arr[i])
			}
		}
		result = append(result, quicksort(low)...)
		result = append(result, equal...)
		result = append(result, quicksort(high)...)
	}else {
		equal = arr
	}
	return result
}

func coord_slice(solid *stl.Solid) ([][3]float64, [][3]float64, [][3]float64) {

	tmp := atama(solid)

	var num_mesh = len(solid.Triangles)
	var x_coords = make([][3]float64, num_mesh*3)
	var y_coords = make([][3]float64,num_mesh*3)
	var z_coords = make([][3]float64, num_mesh*3)

	for i:=0; i<num_mesh; i++ {
		for j := 0; j < 3; j++ {
			x_coords[i*3+j] = [3]float64{float64(i),float64(j),float64(tmp.Triangles[i].Vertices[j][0])}
			y_coords[i*3+j] = [3]float64{float64(i),float64(j),float64(tmp.Triangles[i].Vertices[j][1])}
			z_coords[i*3+j] = [3]float64{float64(i),float64(j),float64(tmp.Triangles[i].Vertices[j][2])}
		}
	}
	return x_coords, y_coords, z_coords
}
