### ISSUE TITLE
Vec3 methods are private

### ISSUE THREAD

**Issue by tjhowse** [hschendel/stl#6]
I am using this module to import STL files. I'd like to be able to do maths on the results, however the methods on stl.Vec3 are all private, which means I need to convert stl.Vec3 into an internal representation. Would you be amenable to a PR that either A) Makes the stl.Vec3 methods public (add, diff, cross, etc), or B) Adds public accessors for each dimension (stl.Vec3.X(), stl.Vec3.Y(), stl.Vec3.Z()) such that I can implement the maths methods in my own code via an interface?

Cheers,
tjhowse.

**Comment by hschendel** [comment]
Hi @tjhowse, sounds reasonable to me. If you still need it, I just pushed it to master.
I would appreciate a PR with a bit more test coverage for Vec3 ;-)
